/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-04-20 06:18:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Ex1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"Ex1\" method=\"post\" size=\"1\">\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"name\">이름</label>\r\n");
      out.write("\t<input type=\"text\" id=\"name\" />\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"code\">주민등록 번호</label>\r\n");
      out.write("\t<input type=\"text\" id=\"code1\"/>-<input type=\"password\" id=\"code2\"/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"id\">아이디</label>\r\n");
      out.write("\t<input type=\"text\" id=\"id\" name=\"id\">\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<label for=\"pwd\">비밀번호</label>\r\n");
      out.write("\t<input type=\"password\" id=\"pwd\" name=\"pwd\"/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"pwd_check\">비밀번호 확인</label>\r\n");
      out.write("\t<input type=\"password\" id=\"pwd_check\" name=\"pwd_check\">\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"email\">이메일</label>\r\n");
      out.write("\t<input type=\"text\" id=\"email1\" class=\"box\" name=\"email1\"/>@<input type=\"text\" id=\"email2\"/>\r\n");
      out.write("\t<select id=\"email_select\">\r\n");
      out.write("\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"postcode\">우편번호</label>\r\n");
      out.write("\t<input type=\"text\" id=\"postCode1\" name=\"postCode\"/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"adress\">주소</label>\r\n");
      out.write("\t<input type=\"text\" id=\"adress1\" name=\"adress1\"/>\r\n");
      out.write("\t<input type=\"text\" id=\"adress2\" name=\"adress2\"/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"hp\">핸드폰번호</label>\r\n");
      out.write("\t<input type=\"text\" id=\"hp\" name=\"hp\">\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"job\">직업</label>\r\n");
      out.write("\t<select id=\"job\">\r\n");
      out.write("\t<option value=\"학생\">학생</option>\r\n");
      out.write("\t<option value=\"컴퓨터/인터넷\">컴퓨터/인터넷</option>\r\n");
      out.write("\t<option value=\"언론\">언론</option>\r\n");
      out.write("\t<option value=\"공무원\">공무원</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label for=\"sns_check\">메일/SMS정보 수신</label>\r\n");
      out.write("\t<input type=\"radio\" id=\"sns_check\" name=\"sns_check\" value=\"수신\"/>수신\r\n");
      out.write("\t<input type=\"radio\" id=\"sns_check\" name=\"sns_check\" value=\"수신거부\"/>수신거부\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<label>관심분야</label>\r\n");
      out.write("\t<input type=\"checkbox\" id=\"inter\" name=\"inter\" value=\"생두\"/>생두\r\n");
      out.write("\t<input type=\"checkbox\" id=\"inter\" name=\"inter\" value=\"원두\"/>원두\r\n");
      out.write("\t<input type=\"checkbox\" id=\"inter\" name=\"inter\" value=\"로스팅\"/>로스팅\r\n");
      out.write("\t<input type=\"checkbox\" id=\"inter\" name=\"inter\" value=\"에스프레소\"/>에스프레소\r\n");
      out.write("\t<input type=\"checkbox\" id=\"inter\" name=\"inter\" value=\"창업\"/>창업\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"submit\" value=\"회원가입\" />\r\n");
      out.write("\t<input type=\"button\" value=\"취소\" onClick=\"history.back();\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
